version: '3'
services:

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./sqlite_data:/app/sqlite_data
    environment:
      - DATABASE_URL=sqlite:///sqlite_data/applications.sqlite



volumes:
  crud_app-db-data:
    name: crud_app-db-data
